ci: add correct test run

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,31 +1,24 @@
 name: Run Tests
 
-# on:
-#   workflow_run:
-#     workflows: [ Build ]
-#     types:
-#       - completed
-
 on:
   push:
-    branches: [ koreshin/self-hosted-runner ]
+    branches: [ master, koreshin/self-hosted-runner ]
+  pull_request:
+    branches: [ master ]
 
 env:
   build_dir: "build"
   config: "Release"
-  artifact: "native"
-  nt: "4"
 
 jobs:
   build:
-    runs-on: ubuntu-24.04
+    name: Build library
+    runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
-
-      - uses: seanmiddleditch/gha-setup-ninja@master
 
       - name: Configure CMake
         run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
@@ -36,40 +29,16 @@ jobs:
       - name: Build library sources
         run: cmake --build ${{ env.build_dir }}
 
-      - name: Upload binary
-        uses: actions/upload-artifact@v4
-        with:
-          name: linux-${{env.artifact}}
-          path: ${{env.build_dir}}/libspla_x64.so
-
-      - name: Archive repository
-        run: tar -cvzf repository.tar.gz ${{ env.build_dir }}/
-
-      - name: Upload build directory
-        uses: actions/upload-artifact@v4
-        with:
-          name: repository
-          path: repository.tar.gz
-
-  deploy:
+  test:
     name: Run tests
     needs: build
     runs-on: self-hosted
-    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    timeout-minutes: 2
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: true
-          fetch-depth: 0
-
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: repository
-      
-      - name: Move artifact to the build directory
-        run: tar -xvzf repository.tar.gz
-
       - name: Run tests
-        run: python3 ./run_tests.py --build-dir=${{ env.build_dir }}
+        run: |
+        python3 ./run_tests.py --build-dir=${{ env.build_dir }} | tee >(grep -qE "FAILED|ERROR" && echo "HAS_ERRORS=true" >> $GITHUB_ENV)
+        if [[ $HAS_ERRORS == "true" ]]; then
+          exit 1
+        fi
